version: '3.8'

volumes:
  postgres_data:
  static_volume:
  media_volume:

services:
  web:
    build: .
    command: gunicorn store_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/

    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=store_username
      - POSTGRES_PASSWORD=301522080595kL
      - POSTGRES_DB=game_store_db
  redis:
    image: redis:7.0.5-alpine
    command: redis-server
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - web

  celery:
    build: .
    command: sh -c 'python manage.py makemigrations && python manage.py migrate && celery -A store_django worker --loglevel=info'
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis