# Generated by Django 4.1.7 on 2023-03-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default='strategia', unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
