# Generated by Django 4.1.7 on 2023-03-29 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainpage',
            options={'verbose_name': 'Главная страница пример', 'verbose_name_plural': 'Главные страницы примеры'},
        ),
    ]
