# Generated by Django 4.1.7 on 2023-03-29 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='inIndex',
        ),
    ]
