# Generated by Django 4.1.7 on 2023-03-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_game_inindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameimage',
            name='image',
            field=models.ImageField(upload_to='games/img', verbose_name='image'),
        ),
    ]
