# Generated by Django 4.1.7 on 2023-03-30 08:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0004_remove_basketitem_in_basket_wishlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WishList',
            new_name='WishItem',
        ),
    ]
