# Generated by Django 4.1.7 on 2023-03-30 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0005_rename_wishlist_wishitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basketitem',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзина'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Оценка', 'verbose_name_plural': 'Оценки'},
        ),
        migrations.AlterModelOptions(
            name='wishitem',
            options={'verbose_name': 'список желаний', 'verbose_name_plural': 'список желаний'},
        ),
        migrations.AlterField(
            model_name='wishitem',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_list', to='games.game'),
        ),
        migrations.AlterUniqueTogether(
            name='wishitem',
            unique_together={('user', 'game')},
        ),
    ]
